services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # mysql does not work on my MacOS.
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
     - "8081:80"
    environment:
      PMA_HOST: db
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=true
      - WORDPRESS_TABLE_PREFIX=mjm1990_
      - WORDPRESS_ICP_NUM=true
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./zh_CN.php:/var/www/html/wp-content/languages/zh_CN.php
volumes:
  db_data:
